"""create assets table

Revision ID: 8a810fe1b5db
Revises: 3900c69a0c05
Create Date: 2026-07-01 14:15:53.995567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a810fe1b5db'
down_revision: Union[str, Sequence[str], None] = '3900c69a0c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.Enum('SERVER', 'WORKSTATION', 'FIREWALL', 'ROUTER', 'SWITCH', 'LAPTOP', 'CLOUD', 'OTHER', name='assettype'), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticality'), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', name='environment'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
